BookSoftware/Account/urls.py
from django.conf.urls import url
from Account import views
app_name='Account'

urlpatterns=[
    url(r'^customer_register/$',views.CustomerRegisterView,name="customer_register"),
    url(r'^manager_register/$',views.ManagerRegisterView,name="manager_register"),
    url(r'^employee_register/$',views.EmployeeRegisterView,name="employee_register"),
    url(r'^login/$',views.LoginView,name="login"),
    url(r'^reset_start/$',views.ResetProcessStartView,name="start_reset"),
    url(r'^reset_password/(?P<user>[-\w]+)/$',views.ResetPasswordView,name="password_reset"),
    url(r'^logout/$',views.user_logout,name="logout"),

]

BookSoftware/BookSoftware/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import settings
from django.conf.urls.static import static
from BookSoftware import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomeView,name="home"),
    url(r'^account/',include('Account.urls',namespace='Account')),
    url(r'^employee/',include('Employee.urls',namespace='Employee')),
    url(r'^customer/',include('Customer.urls',namespace='Customer')),
    url(r'^manager/',include('Manager.urls',namespace='Manager')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookSoftware/Customer/urls.py
from django.conf.urls import url
from Customer import views

app_name="Customer"

urlpatterns=[
    url(r'^$',views.CustomerHomeView.as_view(),name="customer_home"),
    url(r'^search_book/(?P<query>[-\w\s]+)/$',views.BookSearchView,name="search_book"),
    url(r'^book_details/(?P<pk>\d+)/$',views.BookDetailView.as_view(),name="detail_book"),
    url(r'^add_wishlist/$',views.AddWishlistView,name="add_wishlist"),
    url(r'^wishlist_view/(?P<user>[-\w]+)/$',views.WishlistView.as_view(),name="list_wish"),
    url(r'^wishlist_changes/$',views.DeleteWishList,name="delete_wishlist"),
    url(r'^cart/(?P<user>[-\w]+)/$', views.CartView.as_view(), name="view_cart"),
    url(r'^cart_changes/$',views.ChangeCart,name="cart_change"),
    url(r'^change_quantity/$',views.ChangeQuantityView,name="change_quantity"),
    url(r'^add_address/$',views.AddAddressView,name="address_add"),
    url(r'^order_placed/$',views.SuccessOrderView,name="order_success"),
    url(r'^view_transactions/$',views.TransactionView,name="view_transaction"),
    url(r'^suggest/$',views.SuggestView,name="suggest"),
    url(r'^suggest_next/$',views.SuccessSuggest,name="suggest_success"),



]

BookSoftware/Customer/models.py
from django.db import models
from django.contrib.auth import get_user_model
from Employee.models import Book


User=get_user_model()

class UserProduct(models.Model):
    customer=models.ForeignKey(User,related_name="userproduct",on_delete=models.CASCADE)
    product=models.ForeignKey(Book,related_name="userproduct",on_delete=models.CASCADE)
    wishlist=models.BooleanField(default=False)
    cart=models.BooleanField(default=False)
    quantity=models.IntegerField(default=1)

class Address(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    pincode=models.IntegerField()
    addrs=models.CharField(max_length=100)
    locality=models.CharField(max_length=100)
    city=models.CharField(max_length=50)
    state=models.CharField(max_length=50)

class Bill(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products_list=models.ManyToManyField(UserProduct)
    bill_amount=models.DecimalField(max_digits=10,decimal_places=2)
    date=models.DateTimeField()
    address=models.ForeignKey(Address,on_delete=models.CASCADE)

class Suggestion(models.Model):
    book=models.CharField(max_length=200)
    author_name=models.CharField(max_length=200,null=True,blank=True)
    people_count=models.IntegerField()

    def __str__(self):
        if self.book != "":
            return self.book
        elif self.author_name != "":
            return self.author_name

BookSoftware/Customer/forms.py
from django import forms

class SearchForm(forms.Form):
    query=forms.CharField(widget=forms.TextInput)

BookSoftware/Customer/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.urls import reverse
from django.template.loader import get_template
from Customer import forms
from django.core.mail import send_mail,EmailMultiAlternatives
from django.contrib.auth import settings
from django.contrib.auth import get_user_model
from Employee.models import Book
from Customer.models import UserProduct,Address,Bill,Suggestion
import datetime

User=get_user_model()
# Create your views here.
class CustomerHomeView(generic.TemplateView):
    template_name="Customer/customer_home.html"

    def post(self,request,*args,**kwargs):
        search_param = request.POST.get('query')
        return HttpResponseRedirect(reverse('Customer:search_book',kwargs={'query':search_param}))

    def get(self, request, *args, **kwargs):
        return render(request,"Customer/customer_home.html",{'cur_user':request.user})




def BookSearchView(request,query):
    try:
        search_list_by_title = Book.objects.filter(title__icontains=query)
        search_list_by_author = Book.objects.filter(author__icontains=query)
    except:
        return HttpResponse("No such author or book!!")

    total_list = []
    if len(search_list_by_title) != 0:
        total_list += search_list_by_title
    if len(search_list_by_author) != 0:
        total_list += search_list_by_author
    context={}
    temp=request.user.userproduct.all()
    user_product_list=[]
    wish_list=[]
    cart_list=[]
    for k in temp:
        if k.wishlist:
            wish_list.append(k.product.pk)
        if k.cart:
            cart_list.append(k.product.pk)
        user_product_list.append(k.product.pk)
    context['prod_list']=user_product_list
    context['wish_list']=wish_list
    context['cart_list']=cart_list
    return render(request,"Customer/search_query.html",{'list':total_list,'cur_user':request.user,'context':context})

class BookDetailView(generic.DetailView):
    model=Book
    template_name="Customer/detail_book.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['cur_user']=self.request.user
        req_book=Book.objects.get(pk=self.kwargs.get('pk'))
        temp = self.request.user.userproduct.all()
        context['wish_list'] =False
        context['cart_list'] =False
        for k in temp:
            if k.product.pk==req_book.pk:
                if k.wishlist:
                    context['wish_list']=True
                if k.cart:
                    context['prod_list']=True


        return context

def AddWishlistView(request):
    pk=request.GET['pk']
    book=Book.objects.get(pk=pk)
    user=request.user
    data={}
    prod_exist=False
    try:
        prod=UserProduct.objects.get(customer=user,product=book)
        prod_exist=True
    except:
        user_prod=UserProduct.objects.create(customer=user,product=book)
    if not prod_exist:
        user_prod.wishlist=True
        user_prod.save()
    data['prod_exist']=prod_exist
    return JsonResponse(data)

class WishlistView(generic.ListView):
    model=UserProduct
    template_name="Customer/wishlist.html"

    def get_queryset(self):
        cur_user = User.objects.get(username=self.kwargs.get('user'))
        self.temp = cur_user.userproduct.filter(wishlist=True)

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs);
        context['wishlist']=self.temp
        context['length']=len(self.temp)
        context['cur_user']=User.objects.get(username=self.kwargs.get('user'))
        return context

def DeleteWishList(request):
    pk=request.GET['pk']
    job=request.GET['job']
    book=Book.objects.get(pk=pk)
    user_prod=UserProduct.objects.get(customer=request.user,product=book)
    if job=="move_cart":
        user_prod.wishlist=False
        user_prod.cart=True
        user_prod.save()
    elif job=="remove":
        user_prod.delete()

    data={'message':"Book added to cart"}
    return JsonResponse(data)

def ChangeCart(request):
    pk = request.GET['pk']
    job = request.GET['job']
    book = Book.objects.get(pk=pk)
    user_prod = UserProduct.objects.get(customer=request.user, product=book)
    if job == "move_wishlist":
        user_prod.wishlist =True
        user_prod.cart = False
        user_prod.save()
    elif job == "remove":
        user_prod.delete()

    data = {'message': "Book added to wishlist!"}
    return JsonResponse(data)

class CartView(generic.ListView):
    model=UserProduct
    template_name = "Customer/cart.html"

    def get_queryset(self):
        self.sum_of_prices=0;
        cur_user = User.objects.get(username=self.kwargs.get('user'))
        self.temp = cur_user.userproduct.filter(wishlist=False,cart=True)
        for item in self.temp:
            self.sum_of_prices+=item.product.price*item.quantity;

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs);
        context['cartlist'] = self.temp
        context['cur_user'] = User.objects.get(username=self.kwargs.get('user'))
        context['numbers']=range(1,10);
        context['sum_of_prices']=self.sum_of_prices
        context['length'] = len(self.temp)
        return context
def ChangeQuantityView(request):
    pk=request.GET['pk']
    no=request.GET['no']
    book = Book.objects.get(pk=pk)
    user_prod = UserProduct.objects.get(customer=request.user, product=book)
    user_prod.quantity=int(no)
    user_prod.save()
    amt=book.price*int(no)
    data={'amount': amt}
    return JsonResponse(data)

def AddAddressView(request):
    if request.method=="POST":
        name=request.POST['name']
        phone_no = request.POST['phone_no']
        email=request.POST['email']
        pincode = request.POST['pincode']
        addrs= request.POST['addrs']
        locality= request.POST['locality']
        city = request.POST['city']
        state= request.POST['state']
        addr=Address.objects.create(user=request.user,pincode=pincode,addrs=addrs,locality=locality,city=city,state=state)
        final_prod=request.user.userproduct.filter(cart=True)
        total_price=0
        for i in final_prod:
            bk=Book.objects.get(pk=i.product.pk)
            bk.no_of_copies-=i.quantity
            bk.save()
            total_price+=i.product.price*i.quantity
        context={'final_prod':final_prod,'total_price':total_price}
        recipient=email
        subject="Greetings from Book Cafe!"
        with open(settings.BASE_DIR+"/Customer/templates/Customer/invoice.txt") as fl:
            tell_message=fl.read()
        message=EmailMultiAlternatives(subject=subject,
                  body=tell_message, from_email=settings.EMAIL_HOST_USER, to=[recipient])
        html_template=get_template("Customer/invoice.html").render(context=context)
        message.attach_alternative(html_template,"text/html")
        message.send()
        bill_obj=Bill(user=request.user,address=addr,bill_amount=total_price,date=datetime.datetime.now())
        bill_obj.save()
        bill_obj.products_list.set(final_prod)
        for prod in final_prod:
            prod.cart=False
            prod.save()
        #send_mail(subject,
                  #message, settings.EMAIL_HOST_USER, [recipient], fail_silently=False)
        return HttpResponseRedirect(reverse("Customer:order_success"))

    else:
        return render(request,"Customer/address.html",{'cur_user':request.user})


def SuccessOrderView(request):
    return render(request,"Customer/order_placed.html")

def TransactionView(request):
    try:
        all_bills=Bill.objects.filter(user=request.user)
    except:
        all_bills=[]
    return render(request,"Customer/transactions.html",{'all_bills':all_bills,'cur_user':request.user})


def SuggestView(request):
    if request.method=="POST":
        bk_name = request.POST.get('book_name')
        author = request.POST.get('author')
        print(bk_name)
        print(author)
        if bk_name == "" and author == "":
            messages.error(request, "Enter book title or author name!")
            return render(request, "Customer/suggestions.html", {'cur_user': request.user})
        try:
            exist_books = Book.objects.filter(title__icontains=bk_name)
        except:
            exist_books = []
        if len(exist_books) == 0:
            exist_suggestion = Suggestion.objects.filter(book__icontains=bk_name)
            if len(exist_suggestion)==0:
                exist_suggestion_ex = Suggestion(book=bk_name)
                if author != "":
                    exist_suggestion_ex.author_name = author
                    exist_suggestion_ex.people_count = 0
                    exist_suggestion_ex.save()
            else:
                for i in exist_suggestion:
                    i.people_count+=1
                    i.save()





        else:
            return HttpResponseRedirect(reverse('Customer:search_book', kwargs={'query': bk_name}))

        return HttpResponseRedirect(reverse("Customer:suggest_success"))

    return render(request,"Customer/suggestions.html",{'cur_user':request.user,'message':0})

def SuccessSuggest(request):
    return render(request, "Customer/success_suggestion.html", {'cur_user': request.user})

BookSoftware/Customer/templates/Customer/cart.html
{% extends 'Customer/customer_home.html' %}
{% block form_block %}
{% endblock %}
{% block body_block %}
{% ifequal length 0 %}
<h1 align="center" >No items added to cart !</h1>
{% else %}
<div style="margin-left:900px" >

    <table id="table" style="width:400px">
        <tr>
            <th>Title</th>
            <th >Quantity</th>
            <th>Price</th>
        </tr>
{% for item in cartlist %}
{% if item.cart %}
<tr>
    <td>{{item.product.title}}</td>
    <td  id="table_data{{item.product.pk}}" align="center">{{item.quantity}}</td>
    <td id="table_data_price{{item.product.pk}}">{% widthratio item.product.price 1 item.quantity %}</td>
</tr>
{% endif %}
{% endfor %}
<tr>
    <td style="font-size:20px;border:1px" align="center" id="total_sum">TOTAL: Rs.{{sum_of_prices}}</td>
</tr>
        </table>

<a style="margin-left:40px;width:200px" class="btn btn-primary" href="{% url 'Customer:address_add' %}">Place order</a>
</div>
{% endifequal %}

<div class="row">
    <div class="container">
    <div class="col">
{% for j in cartlist %}
{% if j.cart %}
<dialog id="show_up">Book has been added to wishlist!</dialog>
    <div id="card{{j.product.pk}}" class="card" style="width:500px">

    <a href="{{ j.product.book_pic.url }}">
                  <img
                    src="{{ j.product.book_pic.url }}"
                    class="rounded-circle"
                    width="180px"
                    height="200px"
                    style="margin-top:20px"
                  />
                </a>
    <div id="price{{j.product.pk}}" style="margin-left:460px;margin-top:0px;font-size:20px;font-style:bold">
            Rs.{% widthratio j.product.price 1 j.quantity %}
        </div>
        <div class="card-body">
      <h4 class="card-title" style="font-size:20px">{{j.product.title}}</h4>
     <p class="card-text" style="font-size:15px"><strong>{{j.product.author}}</strong></p>
     <p class="card-text">
      <strong>Publications: </strong>{{j.product.publications}}

      </p>
            <label for="quantity">Number of books:</label>
        <select name="quantity" id="quantity" class="qua" onchange="change_number({{j.product}})">
{% for k in numbers %}
{% ifequal k j.quantity %}
            <option id="{{j.product.pk}}" name={{j.product.pk}} selected>{{k}}</option>
            {% else %}
            <option id="value{{j.product.pk}}" name={{j.product.pk}}>{{k}}</option>
            {% endifequal %}
            {% endfor %}
        </select>

    </div>
    <div class="card-footer">
        <button onclick="remove_from_cart({{j.product.pk}})" style="width:300px;font-size:15px" class="btn btn-default">
            Remove</button>

        <button onclick="move_wishlist({{j.product.pk}})" style="width:300px;font-size:15px" class="btn btn-default">
            Move to wishlist</button>



        </div>
    </div>

{% endif %}

 {% endfor %}
        </div>
        </div>
    </div>

<script>
    function move_wishlist(pk_val){
    var div_elem=$("#card"+pk_val);
    var diag=$("#show_up");
    $.ajax({
        type:'GET',
        url:"{% url 'Customer:cart_change' %}",
        data:{
        pk:pk_val,
        job:"move_wishlist",
        },
        success:function(data){
        div_elem.html("");
        diag.show();
        }
        });
    }
    function remove_from_cart(pk_val){
     var div_elem=$("#card"+pk_val);
    $.ajax({
        type:'GET',
        url:"{% url 'Customer:cart_change' %}",
        data:{
        pk:pk_val,
        job:"remove",
        },
        success:function(data){
        div_elem.html("");
        alert("Book has been removed from cart");
        }
        });
    }

    $(document).ready(function(){
    $("select.qua").change(function(){
    var price;
    var sum=0;
    var table=$("#table");
        var selectedVal= $(this).children("option:selected").val();
        var selectedProdId=$(this).children("option:selected").attr("name");

         $.ajax({
        type:'GET',
        url:"{% url 'Customer:change_quantity' %}",
        data:{
        pk:parseInt(selectedProdId),
        no:parseFloat(selectedVal),
        },
        success:function(data){
        $("#price"+parseInt(selectedProdId)).html(data.amount);
        $("#table_data"+parseInt(selectedProdId)).html(parseFloat(selectedVal));

        $("#table_data_price"+parseInt(selectedProdId)).html(data.amount);
        table.find('tr').each(function (i, el) {
        var $tds = $(this).find('td'),
            price= $tds.eq(2).text();
            if(price!==""){
            console.log(price);
            sum+=parseInt(price);
            }

    });

    $("#total_sum").html("TOTAL:  Rs."+sum.toString());

        }
        });
    });
});


</script>
{% endblock %}

BookSoftware/Customer/templates/Customer/customer_home.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/Employee.css' %}">
    <script src="{% static 'js/Employee.js' %}"></script>

</head>
<body>

 <nav class="navbar navbar-expand-lg fixed-top shadow navbar-dark navbar-offcanvas" style="background-color: #155592;">

        <a style="font-size:40px;color:white" class="navbar-brand mr-auto" href="#">Readers Cafe</a>


        <button style="margin-left:1200px" class="navbar-toggler d-block" type="button" id="navToggle">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-simple" style="font-size:25px" href="{% url 'Account:logout' %}">Logout</a></li>
        </ul>
        <div class="navbar-collapse offcanvas-collapse">
            <p class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Customer:customer_home' %}">Dashboard</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Customer:list_wish' user=cur_user.username %}">Wishlist</a>
                </li>
                 <p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Customer:view_cart' user=cur_user.username %}">Cart</a>
                </li>
            </p>
                 <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Customer:suggest' %}">Query section</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Customer:view_transaction' %}" >View Transaction</a>
                </li>

            </ul>


        </div>
    </nav>
 {% block form_block %}
 <form method="POST">
     {% csrf_token %}
 <input style="margin-left:500px;width:400px;height:30px" name="query" type="text" placeholder="Enter book title/author" >
 <input style="width:100px" class="btn btn-warning" type="submit">

     </form>
  <br>
 {% endblock %}

{% block body_block %}
{% endblock %}

</body>
</html>

BookSoftware/Customer/templates/Customer/detail_book.html
{% extends 'Customer/customer_home.html' %}
{% block form_block %}
{% endblock %}
{% block body_block %}
<div class="container">
    <div class="list-group" style="height:350px;margin-top:90px">
        <h1 class="list-group-item-text"><strong>Title: </strong>{{book.title}}</h1>
        <h2 class="list-group-item-text"><strong>Author: </strong>{{book.author}}</h2>
        <h4 class="list-group-item-text"><strong>Genre:  </strong>
        {% for ctg in book.category.all %}
         <li class="list-group-item-text">{{ctg.categ}}</li>
        {% endfor %}
        </h4>
        <h4 class="list-group-item-text"><strong>Publications:</strong>{{book.publications}}</h4>
        <h4 class="list-group-item-text"><strong>Edition: </strong>{{book.edition}}</h4>
        <h4 class="list-group-item-text"><strong>Copies available: </strong>{{book.no_of_copies}}</h4>
        <h4 class="list-group-item-text"><strong>Price:</strong>{{book.price}}</h4>

    </div>
</div>
<div style="margin-left:500px">
     <div class="row">
         {% if wish_list %}
            <div class="col-md-4">
                <button id="wishlisted"  style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                Wishlisted</button>
            </div>

            <div class="col-md-2">
                 <button  onclick="deleteWish({{j.product.pk}})" style="width:200px;font-size:15px" class="btn btn-primary btn-lg">
                  Move to cart</button>
            </div>
        {% elif cart_list %}

                 <button id="cart_add"  style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                  Added to cart</button>

        {% else %}
            <div class="col-md-4">
                  <button id="wish{{cur_user}}{{j.pk}}" onclick="add_item({{j.pk}})" style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                  Add to wishlist</button>
            </div>
            <div class="col-md-2">
                  <button  onclick="deleteWish({{j.product.pk}})" style="width:200px;font-size:15px" class="btn btn-primary btn-lg">
                  Move to cart</button>
            </div>
        {% endif %}
            </div>

    </div>
<script>
 function deleteWish(pk_val){
    var div_elem=$("#card"+pk_val);
    var diag=$("#show_up");
    $.ajax({
        type:'GET',
        url:"{% url 'Customer:delete_wishlist' %}",
        data:{
        pk:pk_val,
        job:"move_cart",
        },
        success:function(data){
        div_elem.html("");
        diag.show();
        }
        });
    }

if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
function add_item(pk_val){
  var user=$("#get_user").val();
  var btn=$("#wish"+user+pk_val);
  var wishl=$("#wishlisted");
  var div_elem=$("#card-footer");
  console.log(btn.val());
  if(btn.val()==="Wishlisted"){
  return false;
  }
  $.ajax({
        type:'GET',
        url:"{% url 'Customer:add_wishlist' %}",
        data:{
        pk:pk_val,
        },
        success:function(data){
        if(!data.prod_exist){
        btn.html("Wishlisted");
        }

        }
        });

}

</script>
{% endblock %}

BookSoftware/Customer/templates/Customer/search_query.html
{% extends 'Customer/customer_home.html' %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
{% block body_block %}


{% for j in list %}

    <div class="card" style="width:500px;margin-left:500px;border:1px solid;height:450px">

    <a href="{{ j.book_pic.url }}">
                  <img
                    src="{{ j.book_pic.url }}"
                    class="rounded-circle"
                    width="180px"
                    height="200px"
                    style="margin-top:20px;margin-left:80px"
                  />
                </a>
    <div class="card-body">
      <h4 class="card-title" style="font-size:30px">{{j.title}}</h4>
     <p class="card-text" style="font-size:20px"><strong>{{j.author}}</strong></p>
     <p class="card-text">
      <strong>Publications: </strong>{{j.publications}}
      <br>
      <strong>Edition: </strong>{{j.edition}}
      <br>
      <strong>Price: </strong>Rs.{{j.price}}
         <br>

     </p>
    </div>

    <input id="get_user" value={{cur_user}} type="hidden">
    <div class="card-footer">
        <div class="row" style="margin-left:50px">


        {% if j.pk in context.wish_list %}
            <div class="col-md-4">
                <button id="wishlisted"  style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                Wishlisted</button>
            </div>

            <div class="col-md-2">
                 <button  onclick="deleteWish({{j.product.pk}})" style="width:200px;font-size:15px" class="btn btn-primary btn-lg">
                  Move to cart</button>
            </div>
        {% elif j.pk in context.cart_list %}

                 <button id="cart_add"  style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                  Added to cart</button>


        {% else %}
            <div class="col-md-4">
                  <button id="wish{{cur_user}}{{j.pk}}" onclick="add_item({{j.pk}})" style="width:150px;font-size:15px" class="btn btn-primary btn-lg">
                  Add to wishlist</button>
            </div>
            <div class="col-md-2">
                  <button  onclick="deleteWish({{j.product.pk}})" style="width:200px;font-size:15px" class="btn btn-primary btn-lg">
                  Move to cart</button>
            </div>
        {% endif %}
            </div>



        </div>
    </div>

<br>
<br>

 {% endfor %}
<script>
 function deleteWish(pk_val){
    var div_elem=$("#card"+pk_val);
    var diag=$("#show_up");
    $.ajax({
        type:'GET',
        url:"{% url 'Customer:delete_wishlist' %}",
        data:{
        pk:pk_val,
        job:"move_cart",
        },
        success:function(data){
        div_elem.html("");
        diag.show();
        }
        });
    }

if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
function add_item(pk_val){
  var user=$("#get_user").val();
  var btn=$("#wish"+user+pk_val);
  var wishl=$("#wishlisted");
  var div_elem=$("#card-footer");
  console.log(btn.val());
  if(btn.val()==="Wishlisted"){
  return false;
  }
  $.ajax({
        type:'GET',
        url:"{% url 'Customer:add_wishlist' %}",
        data:{
        pk:pk_val,
        },
        success:function(data){
        if(!data.prod_exist){
        btn.html("Wishlisted");
        }

        }
        });

}

</script>
{% endblock %}