BookSoftware/Account/urls.py
from django.conf.urls import url
from Account import views
app_name='Account'

urlpatterns=[
    url(r'^customer_register/$',views.CustomerRegisterView,name="customer_register"),
    url(r'^manager_register/$',views.ManagerRegisterView,name="manager_register"),
    url(r'^employee_register/$',views.EmployeeRegisterView,name="employee_register"),
    url(r'^login/$',views.LoginView,name="login"),
    url(r'^reset_start/$',views.ResetProcessStartView,name="start_reset"),
    url(r'^reset_password/(?P<user>[-\w]+)/$',views.ResetPasswordView,name="password_reset"),
    url(r'^logout/$',views.user_logout,name="logout"),

]

BookSoftware/BookSoftware/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import settings
from django.conf.urls.static import static
from BookSoftware import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomeView,name="home"),
    url(r'^account/',include('Account.urls',namespace='Account')),
    url(r'^employee/',include('Employee.urls',namespace='Employee')),
    url(r'^customer/',include('Customer.urls',namespace='Customer')),
    url(r'^manager/',include('Manager.urls',namespace='Manager')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookSoftware/Manager/urls.py
from django.conf.urls import url
from Manager import views
app_name="Manager"

urlpatterns=[
    url(r'^home/$',views.ManagerHomeView.as_view(),name="home_manager"),
    url(r'^bills_list/$',views.BillView.as_view(),name="bill_view"),
    url(r'^sales/$',views.SalesStatisticsView.as_view(),name="statistics"),
    url(r'^books_list/$',views.ManagerBookList.as_view(),name="list_books"),
    url(r'^update_book/(?P<pk>\d+)/$',views.UpdateBook.as_view(),name="update_book"),
    url(r'^delete_book/(?P<pk>\d+)/$',views.DeleteBook.as_view(),name="delete_book"),
    url(r'^view_suggestions/$',views.ViewSuggestions.as_view(),name="view_suggestion"),
    url(r'^threshold_view/$',views.ThresholdView.as_view(),name="threshold"),
    url(r'^categorywise_list/(?P<categ>[-\w\b\w]+)/$',views.ViewCategoryWise.as_view(),name="category_wise"),
]

BookSoftware/Manager/models.py
from django.db import models

# Create your models here.

BookSoftware/Manager/views.py
from django.shortcuts import render
from django.views import generic
from django.http import JsonResponse
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.core import serializers
from Customer.models import Bill,Suggestion
from Employee.models import BookCategory,Book
import json

# Create your views here.
class ManagerHomeView(generic.TemplateView):
    template_name="Manager/manager_home.html"

class BillView(generic.ListView):
    model=Bill
    context_object_name ="bills"
    template_name="Manager/bills_list.html"

class SalesStatisticsView(generic.TemplateView):
    template_name ="Manager/sales_statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bk_categ=BookCategory.objects.all()
        category_list=[]
        for i in bk_categ:
            category_list.append(i.categ)
        categ_list=json.dumps(category_list)
        context['category_list']=categ_list
        chart=self.get_dict(category_list)
        chart_data=json.dumps(chart)
        context['chart_data']=chart_data
        print(chart)
        return context

    def get_dict(self,p):
        d={}
        chart=[]
        bill_products=[]
        all_bills=Bill.objects.all()
        for bill in all_bills:
            prod_list=bill.products_list.all()
            for prod in prod_list:
                bill_products.append(prod)
        for k in bill_products:
            for ctg in k.product.category.all():
                if ctg.categ in d:
                    d[ctg.categ]+=k.quantity
                else:
                    d[ctg.categ]=k.quantity


        for e in p:
            if e in d:
                chart.append(d[e])
            else:
                chart.append(0)
        return chart

class ManagerBookList(generic.ListView):
    model=Book
    context_object_name ="books_list"
    template_name="Manager/books_list.html"





    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        all_categ=BookCategory.objects.all()
        categ_list=[]
        for item in all_categ:
            categ_list.append(item.categ)
        context['categ_list']=categ_list
        li = serializers.serialize("json",Book.objects.all())
        context['json_li']=json.loads(li)
        context['ctg']=""
        context['length']=len(categ_list)
        return context





class UpdateBook(generic.UpdateView):
    model=Book
    fields="__all__"
    template_name="Employee/book_create.html"
    success_url =reverse_lazy("Manager:list_books")

class DeleteBook(generic.DeleteView):
    model=Book
    context_object_name ="bk"
    success_url = reverse_lazy("Manager:list_books")
    template_name ="Manager/confirm_delete.html"




class ViewCategoryWise(generic.ListView):
    model=Book
    template_name ="Manager/books_list.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        ctg=self.kwargs.get('categ')
        bk_obj = Book.objects.all()
        bk_list = []
        pk_list = []
        for book in bk_obj:
            for a in book.category.all():
                if ctg == a.categ and book.pk not in pk_list:
                    pk_list.append(book.pk)
                    bk_list.append(book)
        li = serializers.serialize("json", bk_list)
        all_categ = BookCategory.objects.all()
        categ_list = []
        for item in all_categ:
            categ_list.append(item.categ)
        context['json_li']=json.loads(li)
        context['categ_list']=categ_list
        context['ctg']=ctg
        context['length']=len(bk_list)
        return context




class ViewSuggestions(generic.ListView):
    model=Suggestion
    ordering = ['-people_count']
    context_object_name ="sug_list"
    template_name="Manager/suggestions_view.html"

class ThresholdView(generic.ListView):
    model=Book
    template_name ="Manager/threshold.html"

    def get_queryset(self):
        self.books_list=Book.objects.all()

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        bk_li=[]
        for bk in self.books_list:
            q=bk.initial_copies
            value=(30*q)//100
            if bk.no_of_copies<=value:
                bk_li.append(bk)
        context['books_list']=bk_li
        context['length']=len(bk_li)
        return context

BookSoftware/Manager/templates/Manager/bills_list.html
{% extends 'Manager/manager_home.html' %}
{% block body_block %}
<h2 style="margin-left:350px"><b>BILLS LIST</b></h2>
{% for i in bills %}
 <div class="list-group" style="width:620px;margin-left:350px">
        <div  class="list-group-item" >
            <strong>Customer:</strong>{{i.user.customer.fullname}}
            <strong style="margin-left:30px">Contact number:</strong>{{i.user.customer.phone_no}}
            <h5 class="list-group-item-text"><strong>Order date:</strong>{{i.date}}</h5>
            <h5 class="list-group-item-text"><strong>Bill Amount:</strong>{{i.bill_amount}}</h5>

        </div>
 </div>
{% endfor %}
{% endblock %}

BookSoftware/Manager/templates/Manager/books_list.html
{% extends 'Manager/manager_home.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block body_block %}
<div style="margin-left:1250px">
    <label for="categ" style="font-size:25px">Choose book category</label>

<select name="category_select" id="categ" class="ctg" style="margin-left:60px;width:140px;height:25px" >
    <option>All categories</option>
    {% for i in categ_list %}
    {% ifnotequal ctg "" %}
    {% ifequal ctg i %}
    <option name="{{i}}" selected>{{i}}</option>
    {% else %}
    <option name="{{i}}">{{i}}</option>
    {% endifequal %}

    {% else %}
     <option name="{{i}}">{{i}}</option>
    {% endifnotequal %}
    {% endfor %}
</select>

    </div>
{{ json_li|json_script:"hello-data" }}
<div id="div_elem">

{% ifequal length 0 %}
    <h2 align="center">No books found!</h2>
    {% endifequal %}

{% for j in json_li %}

<div class="row" style="margin-left:350px;border:1px solid;width:900px;height:250px">
    <div class="col-md-4" >
        <a href="/media/book_pictures/{{ j.fields.book_pic }}">
                  <img
                    src="/media/{{ j.fields.book_pic }}"
                    class="rounded-circle"
                    width="180px"
                    height="200px"
                    style="margin-top:20px"
                  />
                </a>
    </div>
        <div class="col-md-4">

      <h4  style="font-size:30px">{{j.fields.title}}</h4>
     <p style="font-size:20px"><strong>Author: </strong>{{j.fields.author}}</p>
     <p>
      <strong>Publications: </strong>{{j.fields.publications}}
      <br>
      <strong>Price: </strong>Rs.{{j.fields.price}}
         <br>
         <strong>No of copies: </strong>{{j.fields.no_of_copies}}
     </p>
    </div>
<div class="col-md-4" style="margin-top:80px">
       <a href="{% url 'Manager:update_book' pk=j.pk %}" style="width:120px" class="btn btn-primary">Update</a>
<a href="{% url 'Manager:delete_book' pk=j.pk %}" style="width:120px" class="btn btn-primary">Delete</a>
    </div>

    </div>


<br>

{% endfor %}
    </div>
<script>
console.log(JSON.parse(document.getElementById('hello-data').textContent));
     $(document).ready(function(){
    $("#categ").change(function(){
    var categ=$(this).children("option:selected").val();
    var c=$(this).children("option:selected");
    var url1="/manager/categorywise_list/"+categ;
    var value = JSON.parse(document.getElementById('hello-data').textContent);
    console.log(value);

$.ajax({
    type:'GET',
    url:url1,
    data:{
    categ:categ,
    },
    success:function(data){

    window.location=url1;

    }
    });

    });

    });

</script>
{% endblock %}

BookSoftware/Manager/templates/Manager/confirm_delete.html
{% extends 'Manager/manager_home.html' %}
{% block body_block %}
<form method="POST">
    {% csrf_token %}
    <h3>Are you sure of deleting {{bk.title}}?</h3>
    <input type="submit" class="btn btn-primary" value="Confirm">
    <a class="btn btn-primary" href="{% url 'Manager:list_books' %}">Cancel</a>
</form>
{% endblock %}

BookSoftware/Manager/templates/Manager/manager_home.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/Employee.css' %}">
    <script src="{% static 'js/Employee.js' %}"></script>

</head>
<body>

 <nav class="navbar navbar-expand-lg fixed-top shadow navbar-dark navbar-offcanvas" style="background-color: #155592;">

        <a style="font-size:40px;color:white" class="navbar-brand mr-auto" href="#">Readers Cafe</a>


        <button style="margin-left:1100px" class="navbar-toggler d-block" type="button" id="navToggle">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-simple" style="font-size:25px;color:white" href="{% url 'Account:logout' %}">Logout</a></li>
        </ul>

        <div class="navbar-collapse offcanvas-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Manager:home_manager' %}">Dashboard <span class="sr-only">(current)</span></a>
                </li>
                 <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Manager:list_books' %}">Modify books</a>
                </li>
                 <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Manager:view_suggestion' %}">View suggestions</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Manager:bill_view' %}" >Bill details</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Manager:statistics' %}" >Sales statistics</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Manager:threshold' %}" >Threshold books</a>
                </li>

            </ul>


        </div>
    </nav>
{% block body_block %}
{% endblock %}

</body>
</html>

BookSoftware/Manager/templates/Manager/sales_statistics.html
{% extends 'Manager/manager_home.html' %}
{% block body_block %}
<h2 align="center">Sales Statistics</h2>
<canvas id="myChart" width="400" height="400"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
const categ_list={{ category_list | safe }};
const chart_data={{ chart_data | safe }};
console.log(categ_list);
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels:categ_list,
        datasets: [{
            label: 'Number of books sold in each category',
            data:chart_data,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>
{% endblock %}

BookSoftware/Manager/templates/Manager/suggestions_view.html
{% extends 'Manager/manager_home.html' %}
{% load static %}
{% block body_block %}
<h2 style="margin-left:350px"><b>SUGGESTIONS LIST</b></h2>
{% for i in sug_list %}
 <div class="list-group" style="width:620px;margin-left:350px">
        <div  class="list-group-item" >
            <h5 class="list-group-item-text"><strong>Book Title: </strong>{{i.book}}</h5>
            <h5 class="list-group-item-text"><strong>Author Name: </strong>{{i.author_name}}</h5>
            <h5 class="list-group-item-text"><strong>Total suggestions for the book: </strong>{{i.people_count}}</h5>
        </div>
 </div>
{% endfor %}
{% endblock %}

BookSoftware/Manager/templates/Manager/threshold.html
{% extends 'Manager/manager_home.html' %}
{% block body_block %}
<h2 align="center">Current threshold set to 30%</h2>
{% ifequal length 0 %}
<h4 align="center" style="margin-top:100px;color:green"><strong>All books are above threshold value!</strong></h4>
{% endifequal %}
{% for j in books_list %}

<div class="row" style="margin-left:350px;border:1px solid;width:900px;height:250px">
    <div class="col-md-4" >
        <a href="{{ j.book_pic.url }}">
                  <img
                    src="{{ j.book_pic.url }}"
                    class="rounded-circle"
                    width="180px"
                    height="200px"
                    style="margin-top:20px"
                  />
                </a>
    </div>
        <div class="col-md-4">

      <h4  style="font-size:30px">{{j.title}}</h4>
     <p style="font-size:20px"><strong>Author: </strong>{{j.author}}</p>
     <p>
      <strong>Publications: </strong>{{j.publications}}
      <br>
      <strong>Price: </strong>Rs.{{j.price}}
         <br>
         <strong>No of copies: </strong>{{j.no_of_copies}}
     </p>
    </div>

</div>
<br>


{% endfor %}
{% endblock %}