BookSoftware/Account/urls.py
from django.conf.urls import url
from Account import views
app_name='Account'

urlpatterns=[
    url(r'^customer_register/$',views.CustomerRegisterView,name="customer_register"),
    url(r'^manager_register/$',views.ManagerRegisterView,name="manager_register"),
    url(r'^employee_register/$',views.EmployeeRegisterView,name="employee_register"),
    url(r'^login/$',views.LoginView,name="login"),
    url(r'^reset_start/$',views.ResetProcessStartView,name="start_reset"),
    url(r'^reset_password/(?P<user>[-\w]+)/$',views.ResetPasswordView,name="password_reset"),
    url(r'^logout/$',views.user_logout,name="logout"),

]

BookSoftware/BookSoftware/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import settings
from django.conf.urls.static import static
from BookSoftware import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomeView,name="home"),
    url(r'^account/',include('Account.urls',namespace='Account')),
    url(r'^employee/',include('Employee.urls',namespace='Employee')),
    url(r'^customer/',include('Customer.urls',namespace='Customer')),
    url(r'^manager/',include('Manager.urls',namespace='Manager')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookSoftware/Employee/urls.py
from django.conf.urls import url
from Employee import views
app_name="Employee"

urlpatterns=[
    url(r'^$',views.EmployeeHomeView.as_view(),name="emp_home"),
    url(r'^create_book/$',views.BookCreateView.as_view(),name="create_book"),
    url(r'^list_books/$',views.BooksListView.as_view(),name="list_book"),
    url(r'^bill_view/$',views.BillView.as_view(),name="manage_bill"),
]

BookSoftware/Employee/models.py
from django.db import models
from django.contrib.auth import get_user_model


User=get_user_model()

# Create your models here.
class BookCategory(models.Model):
    categ=models.CharField(max_length=100)
    def __str__(self):
        return self.categ




class Book(models.Model):
    title=models.CharField(max_length=100)
    isbn=models.CharField(max_length=13,unique=True)
    author=models.CharField(max_length=50)
    year=models.DateField()
    publications=models.CharField(max_length=200)
    edition=models.IntegerField()
    price=models.DecimalField(max_digits=6,decimal_places=2)
    category=models.ManyToManyField(BookCategory)
    book_pic=models.ImageField(upload_to="book_pictures/")
    no_of_copies=models.IntegerField()
    initial_copies=models.IntegerField()

    def __str__(self):
        return self.title

BookSoftware/Employee/forms.py
from django import forms
from Employee import models


class BookForm(forms.ModelForm):
    year = forms.DateField(widget=forms.DateInput(),input_formats=['%d/%m/%Y'])
    category=forms.ModelMultipleChoiceField(queryset=models.BookCategory.objects.all(),widget=forms.CheckboxSelectMultiple)
    class Meta:
        model=models.Book
        fields=("title","isbn","author","publications","edition","price","no_of_copies","initial_copies","book_pic")

    def clean_isbn(self):
        if len(str(self.cleaned_data['isbn']))!=13:
            raise forms.ValidationError("Incorrect ISBN number")
        return self.cleaned_data['isbn']

    def save(self,commit=True):
        f=super(BookForm,self).save(commit=False)
        f.year=self.cleaned_data['year']
        if commit:
            f.save()
        categories=self.cleaned_data['category']
        f.category.set(categories)

        return f

BookSoftware/Employee/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from Employee import models
from Employee import forms
from Customer.models import Bill


# Create your views here.
class EmployeeHomeView(generic.TemplateView):
    template_name="Employee/emp_home.html"

class BookCreateView(generic.CreateView):
    form_class=forms.BookForm
    success_url=reverse_lazy('Employee:emp_home')
    template_name="Employee/book_create.html"

class BooksListView(generic.ListView):
    model=models.Book
    context_object_name ="books"
    template_name="Employee/all_books_list.html"

class BillView(generic.ListView):
    model=Bill
    context_object_name ="bills"
    template_name="Employee/bills_list.html"

BookSoftware/Employee/templates/Employee/all_books_list.html
{% extends 'Employee/emp_home.html' %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
{% block body_block %}

{% for book in books %}
<div class="card">
    <div class="card-body">
        <div class="row" style="margin-left:350px;border:1px solid;width:900px;height:250px;margin-top:20px">
    <div class="col-md-4" >
        <a href="{{ book.book_pic.url }}">
                  <img
                    src="{{ book.book_pic.url }}"
                    class="rounded-circle"
                    width="180px"
                    height="200px"
                    style="margin-top:20px"
                  />
                </a>
    </div>
        <div class="col-md-4">

      <h4  style="font-size:30px">{{book.title}}</h4>
     <p style="font-size:20px"><strong>Author: </strong>{{book.author}}</p>
     <p>
      <strong>Publications: </strong>{{book.publications}}
      <br>
      <strong>Price: </strong>Rs.{{book.price}}
         <br>
         <strong>No of copies: </strong>{{book.no_of_copies}}
     </p>
    </div>



    </div>
</div>
{% endfor %}

{% endblock %}

BookSoftware/Employee/templates/Employee/bills_list.html
{% extends 'Employee/emp_home.html' %}
{% block body_block %}
<h2 style="margin-left:350px"><b>BILLS LIST</b></h2>
{% for i in bills %}
 <div class="list-group" style="width:620px;margin-left:350px">
        <div  class="list-group-item" >
            <strong>Customer:</strong>{{i.user.customer.fullname}}
            <strong style="margin-left:30px">Contact number:</strong>{{i.user.customer.phone_no}}
            <h5 class="list-group-item-text"><strong>Order date:</strong>{{i.date}}</h5>
            <h5 class="list-group-item-text"><strong>Bill Amount:</strong>{{i.bill_amount}}</h5>

        </div>
 </div>
{% endfor %}
{% endblock %}

BookSoftware/Employee/templates/Employee/book_create.html
{% extends 'Employee/emp_home.html' %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
{% block body_block %}
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary">
</form>
             </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

BookSoftware/Employee/templates/Employee/emp_home.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/Employee.css' %}">
    <script src="{% static 'js/Employee.js' %}"></script>

</head>
<body>

 <nav class="navbar navbar-expand-lg fixed-top shadow navbar-dark navbar-offcanvas" style="background-color: #155592;">

        <a style="font-size:40px;color:white" class="navbar-brand mr-auto" href="#">Readers Cafe</a>


        <button style="margin-left:1100px" class="navbar-toggler d-block" type="button" id="navToggle">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-simple" style="font-size:25px;color:white" href="{% url 'Account:logout' %}">Logout</a></li>
        </ul>

        <div class="navbar-collapse offcanvas-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Employee:emp_home' %}">Dashboard</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Employee:create_book' %}">Add Books</a>
                </li>
                 <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Employee:list_book' %}">Books List</a>
                </li>
                 <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="#">Customer care</a>
                </li>
                <p></p>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Employee:manage_bill' %}">Bill details</a>
                </li>

            </ul>


        </div>
    </nav>
{% block body_block %}
{% endblock %}

</body>
</html>