BookSoftware/Account/urls.py
from django.conf.urls import url
from Account import views
app_name='Account'

urlpatterns=[
    url(r'^customer_register/$',views.CustomerRegisterView,name="customer_register"),
    url(r'^manager_register/$',views.ManagerRegisterView,name="manager_register"),
    url(r'^employee_register/$',views.EmployeeRegisterView,name="employee_register"),
    url(r'^login/$',views.LoginView,name="login"),
    url(r'^reset_start/$',views.ResetProcessStartView,name="start_reset"),
    url(r'^reset_password/(?P<user>[-\w]+)/$',views.ResetPasswordView,name="password_reset"),
    url(r'^logout/$',views.user_logout,name="logout"),

]

BookSoftware/BookSoftware/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include
from django.contrib.auth import settings
from django.conf.urls.static import static
from BookSoftware import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomeView,name="home"),
    url(r'^account/',include('Account.urls',namespace='Account')),
    url(r'^employee/',include('Employee.urls',namespace='Employee')),
    url(r'^customer/',include('Customer.urls',namespace='Customer')),
    url(r'^manager/',include('Manager.urls',namespace='Manager')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BookSoftware/templates/basepage.html
<!DOCTYPE html>
<html lang="en">
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
<nav class="navbar myrole" role="navigation" id="navbar">
    <div class="container">

        <ul class="nav navbar-nav navbar-right">

            <li class="dropdown"><a class="dropdown toggle" style="font-size:25px" data-toggle="dropdown" href="#">Register As
            <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a class="btn btn-simple" href="{% url 'Account:customer_register' %}">Customer</a></li>
                    <li><a class="btn btn-simple" href="{% url 'Account:employee_register' %}">Employee</a></li>
                    <li><a class="btn btn-simple" href="{% url 'Account:manager_register' %}">Manager</a></li>

                </ul>
            </li>

             <li><a class="btn btn-simple" style="font-size:25px" href="{% url 'Account:login' %}">Login</a></li>



        </ul>
    </div>
</nav>
{% block body_block %}
{% endblock %}

</body>
</html>